// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxgktzjhbuohzvkwljiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4Z2t0empoYnVvaHp2a3dsaml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNDU1NDgsImV4cCI6MjA2MzkyMTU0OH0.8kMyKyYv7ll731NzN-nunrAsoLu4pOKBNw5JyL_jpqw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);